name: Custom composite action

author: MxShun

description: Custom composite action
  
inputs:
  your-name:
    description: 'Your name'
    required: false
    default: 'World'
    deprecationMessage: 'This input is deprecated.'

outputs:
  greeting:
    description: 'Greeting'
    value: ${{ steps.greeting.outputs.greeting }}

runs:
  using: "composite"
  steps:
    - id: greeting
      name: Greeting
      if: ${{ runner.os == 'linux' }}
      shell: bash
      working-directory: .
      env:
        GREET: 'Hello'
      run: echo "greeting=$(echo $GREET ${{ inputs.your-name }})" >> $GITHUB_OUTPUT
      continue-on-error: true

branding:
  icon: 'terminal' # https://feathericons.com/
  color: 'green'
