name: Custom docker action

author: MxShun

description: Custom docker action
  
inputs:
  your-name:
    description: 'Your name'
    required: false
    default: 'World'
    deprecationMessage: 'This input is deprecated.'

outputs:
  greeting:
    description: 'Greeting'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - 'World'
  env:
    GREET: 'Hello'
  pre-entrypoint: 'setup.sh' # ローカル アクションではサポートされていません。
  entrypoint: 'main.sh'
  post-entrypoint: 'cleanup.sh'

branding:
  icon: 'cloud' # https://feathericons.com/
  color: 'gray-dark'
