name: List root syntaxes

author: MxShun

description: List root syntaxes
  
inputs:
  your-name:
    description: 'Your name'
    required: false
    default: 'World'
    deprecationMessage: 'This input is deprecated.'

outputs:
  greeting:
    description: 'Greeting'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - 'World'
  env:
    GREET: 'Hello'
  pre-entrypoint: './.github/custom/docker/setup.sh'
  entrypoint: './.github/custom/docker/main.sh'
  post-entrypoint: './.github/custom/docker/cleanup.sh'

branding:
  icon: 'cloud' # https://feathericons.com/
  color: 'gray-dark'
