name: Print runner context

on: workflow_dispatch

jobs:
  # https://docs.github.com/ja/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#runner-context
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print runner context
        run: |
          echo "runner.name: ${{ runner.name }}"
          echo "runner.os: ${{ runner.os }}"
          echo "runner.arch: ${{ runner.arch }}"
          echo "runner.temp: ${{ runner.temp }}"
          echo "runner.tool_cache: ${{ runner.tool_cache }}"
          echo "runner.debug: ${{ runner.debug }}"
          echo "runner.environment: ${{ runner.environment }}"
