name: Test permissions

on: workflow_dispatch

permissions: {}

jobs:
  no-permissions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gh issue create
        run: |
          gh issue create --title "no-permissions-`date -d '9 hours' +'%Y-%m-%d%H:%M:%S'`-label" --body "no-permissions"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  read-permissions:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: gh issue create
        run: |
          gh issue create --title "read-permissions-`date -d '9 hours' +'%Y-%m-%d%H:%M:%S'`-label" --body "read-permissions"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
