name: Test custom actions

on: workflow_dispatch

jobs:
  custom-composite:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: custom-action
      uses: ./.github/custom/composite
    - run: echo ${{ steps.custom-action.outputs.greeting }}

  custom-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: custom-action
      uses: ./.github/custom/docker
    - run: echo ${{ steps.custom-action.outputs.greeting }}

  custom-javascript:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: custom-action
      uses: ./.github/custom/javascript
    - run: echo ${{ steps.custom-action.outputs.greeting }}
